version: '3.8'

services:
  backend:
    build: ./backend
    image: subper_app_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True 
    command: python manage.py runserver 0.0.0.0:8000  
