# Generated by Django 5.0.14 on 2025-08-06 13:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ram', models.PositiveIntegerField(help_text='RAM size in GB')),
                ('storage', models.PositiveIntegerField(help_text='Internal storage in GB')),
                ('cpu_model', models.CharField(max_length=100)),
                ('cpu_score', models.PositiveIntegerField(help_text='CPU benchmark score')),
                ('gpu_model', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size', models.DecimalField(decimal_places=1, help_text='Screen size in inches', max_digits=4)),
                ('battery_capacity', models.PositiveIntegerField(help_text='Battery capacity in mAh')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.laptop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
